### PR TITLE
CI updates

### PR DESCRIPTION
**Pull request by brandon93s**
**Do Not Merge!**

I pushed up a debug binary of https://github.com/sindresorhus/win-wallpaper to grab the error code of the `SystemParametersInfoW` invocation and it looks like [the build environment is Server Core](https://travis-ci.community/t/docker-windows-containers-on-windows/427/2) which doesn't have a GUI.

image

image

---

We have a few options:

1. Leave the build with AppVeyor
2. Explore a docker build, running a GUI server ([compat](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility))
3. Update `win-wallpaper` to continue gracefully in a headless environment

### CODE REVIEW

**Comment by sindresorhus** [comment]
Relevant forum thread: https://travis-ci.community/t/gui-is-not-available-inside-build/1557

**Comment by sindresorhus** [comment]
> Update win-wallpaper to continue gracefully in a headless environment

Since this is a CLI tool, that would be optimal, but not sure how to do that honestly.

**Comment by sindresorhus** [comment]
@brandon93s What should we do with this PR?

**Comment by brandon93s** [comment]
Closing for now until I have time to circle back.

**Pull request closed without merging**
