### PR TITLE
windows shell with forever

### PR DESCRIPTION
**Pull request by FrancoisMentec**
**Context:**
I made a script that update my wallpaper every 10 minutes, and used [forever](https://www.npmjs.com/package/forever) to run it as a daemon.

**Problem:**
Every time it set the wallpaper on windows there is a shell that pop for 0.5 sec and it's quite annoying, especially while playing games or watching movies.

**Solution:**
Use childrenProcess.spawn to set the wallpaper with detached at true and shell at false to prevent the opening of a shell.

### CODE REVIEW

**Comment by FrancoisMentec** [comment]
I added mate support from  @fa7ad and fixed errors from test (mostly typo)

**Comment by sindresorhus** [comment]
`shell: false` is moot as it's the default. Can you try setting `shell: true` instead and not setting `detached: true`.

**Comment by sindresorhus** [comment]
> I added mate support from  [@fa7ad](https://github.com/fa7ad) and fixed errors from test (mostly typo)

That is completely unrelated to this PR and should not be included here.

**Comment by FrancoisMentec** [comment]
> shell: false is moot as it's the default. Can you try setting shell: true instead and not setting detached: true.

Tried, doesn't works, but removed shell false, useless

> I added mate support from  @fa7ad and fixed errors from test (mostly typo)
That is completely unrelated to this PR and should not be included here.

I needed it for a project so it was easier to get all modifications in one repo, probably not the cleanest way to do that.

**Comment by sindresorhus** [comment]
This is better solved in Node.js core: https://github.com/nodejs/node/pull/15380

**Pull request closed without merging**
