### PR TITLE
fix(linux): change import statement

### PR DESCRIPTION
**Pull request by Pierre-Monier**
I tried your package on a personal project and I found some bug. The import statement for Linux were wrong, so I change them

### CODE REVIEW

**Comment by sindresorhus** [comment]
Don't do unrelated changes

**Comment by Pierre-Monier** [comment]
Your plugin wasn't working on linux platform, I thought it was a good idea to fix it

**Comment by sindresorhus** [comment]
You are making style changes that are not related to that.

**Comment by Pierre-Monier** [comment]
Ok my bad, I didn't see that Prettier done that

**Pull request closed without merging**
