### PR TITLE
Add Scaling Feature on Windows

### PR DESCRIPTION
**Pull request by beyluta**
- Update the binary to the latest 2.0.0 version.
- Add the `--scale` flag.

#55 Partial fix for this issue. They later requested the feature for both Windows & Linux
#5   Potential fix for this issue. I don't have multiple monitors, but the last comment mentioned it having to do with the 'tile' property https://github.com/sindresorhus/wallpaper/issues/5#issuecomment-504352736

### CODE REVIEW

**Comment by beyluta** [comment]
My bad, I completely forgot to run the tests. I will take a look at them tomorrow and fix the issues.

**Comment by sindresorhus** [comment]
@beyluta https://github.com/sindresorhus/win-wallpaper/releases/tag/v3.0.0

Would you be able to also add support for ARM64? Could be a separate pull request.

**Comment by beyluta** [comment]
> @beyluta https://github.com/sindresorhus/win-wallpaper/releases/tag/v3.0.0
> 
> Would you be able to also add support for ARM64? Could be a separate pull request.
I'll take a look at it as soon as I can.

**Comment by beyluta** [comment]
Note: I've been having **some** issues running the new binary on my device. 

I am unsure why, but sometimes the backgrounds will fail to be set (they give the error 0x8007007A... but other times, the background does not set and I get no errors).

I googled the issue and it seems it might be something to do with my machine. Although I am unsure what exactly. I also got other error codes but I sadly did not save them and have been unable to reproduce ever since.

**Comment by sindresorhus** [comment]
> I'll take a look at it as soon as I can.

Do you plan to do it in this pull request or a different one?

**Comment by sindresorhus** [comment]
> I am unsure why, but sometimes the backgrounds will fail to be set (they give the error 0x8007007A... but other times, the background does not set and I get no errors).

It may be related to what this is fixing: https://github.com/sindresorhus/win-wallpaper/pull/11

**Comment by beyluta** [comment]
> > I'll take a look at it as soon as I can.
> 
> Do you plan to do it in this pull request or a different one?

Different PR for ARM64 support.

**Comment by sindresorhus** [comment]
Can you update the binary: https://github.com/sindresorhus/win-wallpaper/releases/tag/v3.0.1

**Comment by beyluta** [comment]
> Can you update the binary: https://github.com/sindresorhus/win-wallpaper/releases/tag/v3.0.1

I am still having the same issue. I am using the same images as provided in the root of the directory. `fixture.jpg` and `fixture2.jpg`
```
Error: "Failed to set the desktop wallpaper: The data area passed to a system call is too small. (0x8007007A)"
```

Here is a screenshot of my cmd

image

Running the same command multiple times will eventually succeed. However this time the Wallpaper isn't being set at all.

**Comment by sindresorhus** [comment]
// @tangdaoyuan @a-isaiahharvey Any ideas?

**Comment by a-isaiahharvey** [comment]
Can you try running the program as administrator?

**Comment by beyluta** [comment]
> Can you try running the program as administrator?

Had no effect. Same symptoms.

**Comment by beyluta** [comment]
> Would be nice to make it work for non-admin. But even if not, it should at least show a user-friendly error message instead of crashing.

I'll see what I can do. Would the following error message suffice?
`An error has occurred. Error code: XXX. Have you tried running the program as an administrator?`

I can display something along these lines. The program would still exist with the binary of course. Maybe someone is working to also display something similar?

**Comment by sindresorhus** [comment]
I meant that the binary should do this, not this package.

**Comment by a-isaiahharvey** [comment]
@beyluta Can you try running this binary? 

https://github.com/a-isaiahharvey/WinWallpaper-CPP/releases/tag/1.0.0

For me I found it kind of strange that when I tried implementing nearly the exact same program in C++ I didn't get have any errors on my side nor had to run as administrator.

**Comment by beyluta** [comment]
> @beyluta Can you try running this binary?
> 
> https://github.com/a-isaiahharvey/WinWallpaper-CPP/releases/tag/1.0.0
> 
> For me I found it kind of strange that when I tried implementing nearly the exact same program in C++ I didn't get have any errors on my side nor had to run as administrator.

I tried running the binary but the set command wouldn't work for some reason. I used multiple pictures and formats but it just wouldn't set. I also tried giving the binary (and the cmd) admin privileges. See the image below (Same result using CMD or PowerShell).

I never got any error codes either.

image

**Comment by a-isaiahharvey** [comment]
Hmm. Try this update.
https://github.com/a-isaiahharvey/WinWallpaper-CPP/releases/tag/v1.1.0

I added more error handling and better support for relative file paths

**Comment by a-isaiahharvey** [comment]
> Whatever you did, it seems to have fixed the issue, now the backgrounds are being set. Also works without admin privileges. Scale feature also works nicely.

That's awesome! Now the only thing for me to do is figure out if it's possible to do the same thing in Rust without using admin privileges.

**Comment by sindresorhus** [comment]
> Now the only thing for me to do is figure out if it's possible to do the same thing in Rust without using admin privileges.

@a-isaiahharvey Were you able to look into this?

**Comment by a-isaiahharvey** [comment]
@sindresorhus I tried to fix it from my end and it works. I would still need to verify that "The data area passed to a system call is too small." doesn't happen on another Windows computer to be sure though

**Comment by sindresorhus** [comment]
Could you compile a binary from https://github.com/sindresorhus/win-wallpaper/pull/13 that @beyluta can test?

**Comment by a-isaiahharvey** [comment]
Sure. Here you go:

[wallpaper.zip](https://github.com/sindresorhus/wallpaper/files/11800519/wallpaper.zip)

**Comment by beyluta** [comment]
> Sure. Here you go:
> 
> [wallpaper.zip](https://github.com/sindresorhus/wallpaper/files/11800519/wallpaper.zip)

Worked like a charm on my machine :)

I'll update the pr as soon as the new version of the binary is released.

**Comment by sindresorhus** [comment]
@beyluta https://github.com/sindresorhus/win-wallpaper/releases/tag/v3.0.2

**Comment by sindresorhus** [comment]
Awesome. Thanks for working on this, both of you 👍

**Comment by sindresorhus** [comment]
@beyluta Are you up for doing the ARM64 PR now too? If not, I will do a new release right away.

**Comment by beyluta** [comment]
> @beyluta Are you up for doing the ARM64 PR now too? If not, I will do a new release right away.

You should probably do a new release for now. I'm busy as of recent. I will look into it when I get some more free time.

**Pull request merged**
