### PR TITLE
Add support for mate on linux 

### PR DESCRIPTION
**Pull request by xc0d3rz**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you fix the merge conflict and ensure running `npm test` locally passes.

**Comment by fa7ad** [comment]
@xc0d3rz most of these errors look like they are indentation errors (tabs/spaces). just change your editor settings to tabs and it should be fine :smile:

**Comment by xc0d3rz** [comment]
I Request help :tired_face:

**Comment by fa7ad** [comment]
Okay just give me access to your fork 
screenshot from 2017-06-10 12-50-04

Or, if you dont mind, I could create another PR with your code

**Comment by fa7ad** [comment]
@xc0d3rz Adapted your code in #24. I think you can close this now

**Comment by xc0d3rz** [comment]
Thank you :)

**Pull request closed without merging**
